title: "IASA Articles"
description: "Дізнайтеся про останні події, новини, вступну кампанію та студентське життя в ІПСА."
url: "https://iasastudentcouncil.github.io"
baseurl: "/iasa-sc-blog"
lang: "uk"
robots: "index, follow"

author: "IASA Student Council"
github_username: "IASAStudentCouncil"

head:
  - { name: "charset", content: "utf-8" }
  - { name: "viewport", content: "width=device-width, initial-scale=1.0" }
  - { name: "title", content: "IASA Articles" }
  - { rel: "icon", href: "/img/favicon1.ico", sizes: "16x16", type: "image/x-icon" }
  - { rel: "icon", href: "/img/favicon1.ico", sizes: "32x32", type: "image/x-icon" }
  - { rel: "icon", href: "/img/favicon1.ico", sizes: "48x48", type: "image/x-icon" }
  - { rel: "apple-touch-icon", href: "/img/favicon1.ico", sizes: "180x180" }
  - { name: "description", content: "Офіційний сайт Студентської Ради ІПСА" }
  - { property: "og:title", content: "IASA Articles" }
  - { property: "og:description", content: "Дізнайтеся про останні події, новини, вступну кампанію та студентське життя в ІПСА." }
  - { property: "og:image", content: "/img/IASA-social.jpg" }
  - { property: "og:url", content: "https://iasastudentcouncil.github.io/iasa-sc-blog" }
  - { property: "og:site_name", content: "IASA Articles" }
  - { property: "og:type", content: "website" }
  - { property: "og:locale", content: "uk_UA" }
  - { property: "og:image:alt", content: "IASA Articles" }

google_analytics: "G-9CFDMS82J9"

seo:
  type: "website"
  title: "IASA Articles"
  description: "Дізнайтеся про останні події, новини, вступну кампанію та студентське життя в ІПСА."
  url: "https://iasastudentcouncil.github.io/iasa-sc-blog"
  image: "/img/IASA-social.jpg"
  og:
    title: "IASA Articles"
    description: "Дізнайтеся про останні події, новини, вступну кампанію та студентське життя в ІПСА."
    type: "website"
    image: "/img/IASA-social.jpg"
    url: "https://iasastudentcouncil.github.io/iasa-sc-blog"
    locale: "uk_UA"

sitemap: 
  changefreq: weekly
  priority: 0.7

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - node_modules
  - vendor
  - README.md
