// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  allPostsSidebar: [
    { 
      type: 'autogenerated', 
      dirName: '.', 
    },
  ],

  studentSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', 
      filter: (doc) => doc.frontMatter.tags && doc.frontMatter.tags.includes('студенту'),
    },
  ],

  admissionSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
      filter: (doc) => doc.frontMatter.tags && doc.frontMatter.tags.includes('вступ'),
    },
  ],

  interviewSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
      filter: (doc) => doc.frontMatter.tags && doc.frontMatter.tags.includes('інтервʼю'),
    },
  ],

  councilSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
      filter: (doc) => doc.frontMatter.tags && doc.frontMatter.tags.includes('студрада'),
    },
  ],

  electiveSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
      filter: (doc) => doc.frontMatter.tags && doc.frontMatter.tags.includes('вибіркові'),
    },
  ],
};

module.exports = sidebars;