name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - name: Test Checkout Repository
        uses: actions/checkout@v3

      - name: Test Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Project Dependencies
        run: npm ci

      - name: Test Build Website
        run: npm run build
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}

      - name: Test Display Build Folder Size
        run: du -sh ./build
